apiVersion: v1
kind: Pod
metadata:
  name: quto-mem-cpu-demo-2
spec:
  containers:
  - name: quto-mem-cpu-demo-2
    image: nginx
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"
